from tkinter import*
import mysql.connector
from tkinter import ttk
from tkinter import ttk,messagebox
from tkcalendar import DateEntry
from PIL import Image,ImageTk #pip install Pillow
def login_window():
    rt.destroy()
    import login

def Add():
    if fen.get()=="" or len.get()=="" or cont.get()=="" or courselist.get()=="" or fees.get()=="" or visits.get()=="" or email1.get()==""or pass1.get()=="" or pass2=="":
        messagebox.showerror("Error","All fields are required")
    elif pass1.get()!=pass2.get():
        messagebox.showerror("Error", "Password and confirm password must be same")
    elif vag.get()==0:
        messagebox.showerror("Error", "please agree our term and codition")
    else:
     nm=fen.get()
     lm=len.get()
     cont1=cont.get()
     dob1=cal.get()
     course1=courselist.get()
     gen1=radio.get()
     fee1=fees.get()
     visit1=visits.get()
     e=email1.get()
     password1=pass1.get()
     cpass=pass2.get()
     db=mysql.connector.connect(host="localhost",user="root",password="Soumya123",database="hospital")
     mycursor=db.cursor()
     print("connected")
     try:
        sql="insert into doctor(firstname,lnm,contact,dob,profession,gen,fee,visit,email,password,cpass)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        val=(nm,lm,cont1,dob1,course1,gen1,fee1,visit1,e,password1,cpass)
        mycursor.execute(sql,val)
        db.commit()
        lastid=mycursor.lastrowid
        messagebox.showinfo("information","Record Inserted successfully")
        nm.delete(0,END)
        lm.delete(0, END)
        cont1.delete(0, END)
        dob1.delete(0, END)
        course1.delete(0, END)
        gen1.delete(0, END)
        fee1.delete(0, END)
        visit1.delete(0, END)

        e.delete(0, END)
        password1.delete(0, END)
        cpass.delete(0, END)
        nm.focus_set()
     except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()

rt=Tk()
rt.title("Register")
rt.geometry("1400x700+0+0")

bg2=ImageTk.PhotoImage(file="logbg.jpg")
frame=Label(rt,image=bg2)
frame.place(x=30,y=20,width=1300,height=730)
reg=Label(frame,text="Welcome to SSA Hospital",font=("Charlemagne Std",35,"bold"),fg="white",bg="dark blue")
reg.place(x=230,y=25,width=900)
bg1=ImageTk.PhotoImage(file="gho.jpeg")
logolb=Label(rt,image=bg1)
logolb.place(x=50,y=160,width=500,height=480)
frame=Frame(rt,bg='white')
frame.place(x=520,y=130,width=800,height=540)
reg=Label(frame,text="REGISTER HERE DOCTOR",font=("Times New Roman",25,"bold"),fg="dark blue",bg="White")
reg.place(x=20,y=20)
fnm=Label(frame,text="First Name",font=("Times New Roman",15,"bold"),bg="white")
fnm.place(x=30,y=80)
fen=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
fen.place(x=30,y=110,width=250)
lnm=Label(frame,text="Last Name",font=("Times New Roman",15,"bold"),bg="white")
lnm.place(x=370,y=80)
len=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
len.place(x=370,y=110,width=250)
contact=Label(frame,text="Contact Number",font=("Times New Roman",15,"bold"),bg="white")
contact.place(x=30,y=150)
cont=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
cont.place(x=30,y=180,width=250)
dob=Label(frame,text="DOB",font=("Times New Roman",15,"bold"),bg="white")
dob.place(x=370,y=150)
cal = DateEntry(frame,font=("Times New Roman",15,"bold"),background='gray',foreground='white',borderwidth=2)
cal.place(x=370,y=180,width=250,height=30)
course=Label(frame,text="Profession",bg="white",font=("Times New Roman",15,"bold"))
course.place(x=30,y=210)
courselist=ttk.Combobox(frame,textvariable="vcourse",font=("Times New Roman",15,"bold"),state="readonly")
courselist["values"]=("SELECT","Cardiologist","Orthopaedic","Dentist","ENT specialist","Gynaecologist","Paediatrician","Neurologist","Oncologist")
courselist.place(x=30,y=240,width=250)
courselist.current(0)
gen=Label(frame,text="Gender",font=("Times New Roman",15,"bold"),bg="white")
gen.place(x=370,y=210)
radio = StringVar()
m = Radiobutton(frame,text="Male",variable=radio,value="Male",bg="white",font=("Times New Roman",15,"bold"))
m.place(x=370,y=240,width=130,height=20)
f=Radiobutton(frame, text="Female", variable=radio, value="Female",bg="White",font=("Times New Roman",15,"bold"))
f.place(x=370,y=260,width=150,height=20)

fee3=Label(frame,text="Fees",font=("Times New Roman",15,"bold"),bg="white")
fee3.place(x=30,y=280)
fees=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
fees.place(x=30,y=310,width=250)
visit3=Label(frame,text="Visiting Time",font=("Times New Roman",15,"bold"),bg="white")
visit3.place(x=370,y=280)
visits=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
visits.place(x=370,y=310,width=250)

email=Label(frame,text="Email",font=("Times New Roman",15,"bold"),bg="white")
email.place(x=30,y=340)
email1=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
email1.place(x=30,y=370,width=250)
password=Label(frame,text="Password",font=("Times New Roman",15,"bold"),bg="white")
password.place(x=370,y=340)
pass1=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
pass1.place(x=370,y=370,width=250)
pass1.config(show="*")
cnpassword=Label(frame,text="Confirm Password",font=("Times New Roman",15,"bold"),bg="white")
cnpassword.place(x=370,y=400)
pass2=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
pass2.place(x=370,y=430,width=250)
pass2.config(show="*")
vag=IntVar()
chk=Checkbutton(frame,variable=vag,text="I Agree the Terms and Conditions",font=("Times New Roman",10,"bold"),onvalue=1,offvalue=0)
chk.place(x=370,y=480)
b1=Button(frame,text="Register",command=Add,font=("Times New Roman",15,"bold"),bg="dark blue",fg="white")
b1.place(x=30,y=410)
b2=Button(frame,text="Login",command=login_window,font=("Times New Roman",15,"bold"),bg="dark blue",fg="white")
b2.place(x=30,y=460)

rt.mainloop()